spring:
  profiles:
    include:
      - local

  jwt:
    secret: ZG9uZ2h1bi1zaGFycC1kYnJ1YS13ZWItcHJvamVjdC11c2luZy1qd3Qtc2VjcmV0LURvbmdodW4tc3ByaW5nLWJvb3Qtand0LWJhY2stZW5kLWFuZC1qcy1jb2xsYWJv
    access:
      expiration: 60480
      header: Authorization
    refresh:
      expiration: 86400
      header: Authorization-refresh

  redis:
    host: localhost
    port: 6379

  aws:
    ses:
      access-key: AKIAU5GCOHQL7OAOEH2F
      secret-key: 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

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

cloud:
  aws:
    credentials:
      accessKey: AKIAU5GCOHQL7OAOEH2F
      secretKey: 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
    s3:
      bucket: lifiabucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
