spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:mysql://lifia-db-instance.cbsuxxf8jes5.ap-northeast-2.rds.amazonaws.com:3306/lifia_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: fkdlvldk

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true