spring:
  profiles:
    include:
      - local

  jwt:
    secret: 6e8093a0d65ae3f9d193a04ac378858a76abf71ef73e3e2f74b078c6459d82c9800a299331b1227574c049a489771c128e3e6eed7b4057c44c5c5c119eed3f42
    access:
      expiration: 60480
      header: Authorization
    refresh:
      expiration: 86400
      header: Authorization-refresh

  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

cloud:
  aws:
    ses:
      access-key: AKIAU5GCOHQL7OAOEH2F
      secret-key: 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
    credentials:
      accessKey: AKIAU5GCOHQL7OAOEH2F
      secretKey: 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
    s3:
      bucket: lifiabucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
